service: aws-data-pulley-api

frameworkVersion: '3'

custom:
  wsgi:
    app: run.app

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
